### ISSUE TITLE
Compatibility with Shopware 6.4.11?

### ISSUE THREAD

**Issue by Shoekrates** [Shape-and-Shift/shopware-cms-grid-blocks#10]
Hi, we use your grid plugin within a Shopware installation with version 6.4.11.1 (current).
Since the update from 6.4.9 to 6.4.11 (this is when we realized the problem) the plugin seems to have lost its' compatibility. 
The block group „grid“ doesn't show up in layout module dropdown (where text, image, commerce etc. is chosen) and already built grid elements don't show up in layout mode although they are still visible in the frontend.
Last update was 2 years ago – and since this is a paid plugin, any update planned?

**Comment by ChristopherDosin** [comment]
@Shoekrates We'll have a look into this - We already got the same feedback a few days ago from someone else.
